// Date: 4-9-2014 20:45:53
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package net.minecraft.src;

public class ModelImp extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer rightleg;
    ModelRenderer leftleg;
    ModelRenderer rhorn1;
    ModelRenderer rhorn2;
    ModelRenderer lhorn1;
    ModelRenderer lhorn2;
  
  public ModelImp()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-4F, -8F, -4F, 8, 8, 8);
      head.setRotationPoint(0F, 1F, 0F);
      head.setTextureSize(64, 32);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      body = new ModelRenderer(this, 16, 16);
      body.addBox(-4F, 0F, -2F, 8, 12, 4);
      body.setRotationPoint(0F, 1F, 0F);
      body.setTextureSize(64, 32);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      rightarm = new ModelRenderer(this, 40, 16);
      rightarm.addBox(-3F, -2F, -2F, 4, 12, 4);
      rightarm.setRotationPoint(-5F, 3F, 0F);
      rightarm.setTextureSize(64, 32);
      rightarm.mirror = true;
      setRotation(rightarm, 0F, 0F, 0F);
      leftarm = new ModelRenderer(this, 40, 16);
      leftarm.addBox(-1F, -2F, -2F, 4, 12, 4);
      leftarm.setRotationPoint(5F, 3F, 0F);
      leftarm.setTextureSize(64, 32);
      leftarm.mirror = true;
      setRotation(leftarm, 0F, 0F, 0F);
      rightleg = new ModelRenderer(this, 0, 16);
      rightleg.addBox(-2F, 0F, -2F, 4, 11, 4);
      rightleg.setRotationPoint(-2F, 13F, 0F);
      rightleg.setTextureSize(64, 32);
      rightleg.mirror = true;
      setRotation(rightleg, 0F, 0F, 0F);
      leftleg = new ModelRenderer(this, 0, 16);
      leftleg.addBox(-2F, 0F, -2F, 4, 11, 4);
      leftleg.setRotationPoint(2F, 13F, 0F);
      leftleg.setTextureSize(64, 32);
      leftleg.mirror = true;
      setRotation(leftleg, 0F, 0F, 0F);
      rhorn1 = new ModelRenderer(this, 0, 0);
      rhorn1.addBox(0F, 0F, 0F, 1, 2, 2);
      rhorn1.setRotationPoint(3F, -9F, -1F);
      rhorn1.setTextureSize(64, 32);
      rhorn1.mirror = true;
      setRotation(rhorn1, 0F, 0F, 0F);
      rhorn2 = new ModelRenderer(this, 0, 0);
      rhorn2.addBox(0F, 0F, 0F, 1, 3, 1);
      rhorn2.setRotationPoint(4F, -10F, 0F);
      rhorn2.setTextureSize(64, 32);
      rhorn2.mirror = true;
      setRotation(rhorn2, 0F, 0F, 0F);
      lhorn1 = new ModelRenderer(this, 0, 0);
      lhorn1.addBox(0F, 0F, 0F, 1, 2, 2);
      lhorn1.setRotationPoint(-4F, -9F, -1F);
      lhorn1.setTextureSize(64, 32);
      lhorn1.mirror = true;
      setRotation(lhorn1, 0F, 0F, 0F);
      lhorn2 = new ModelRenderer(this, 0, 0);
      lhorn2.addBox(0F, 0F, 0F, 1, 3, 1);
      lhorn2.setRotationPoint(-5F, -10F, 0F);
      lhorn2.setTextureSize(64, 32);
      lhorn2.mirror = true;
      setRotation(lhorn2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    head.render(f5);
    body.render(f5);
    rightarm.render(f5);
    leftarm.render(f5);
    rightleg.render(f5);
    leftleg.render(f5);
    rhorn1.render(f5);
    rhorn2.render(f5);
    lhorn1.render(f5);
    lhorn2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
